In [59]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

In [60]:
df = pd.read_csv('../../dataset/smart factory machinery data set.csv')
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  str
 2   Type                     10000 non-null  str
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), str(2)
memory usage: 1.1 MB

In [62]:
df.isna().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

# Single Linear Regression

In [63]:
x = df[['Rotational speed [rpm]']]
y = df['Process temperature [K]']

model = LinearRegression()
model.fit(x, y)

model.predict([[1408]])

/home/sanjay/Documents/MLOps training/venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([309.98469705])

# Multivariate Linear Regression

In [64]:
x = df.drop(['UDI', 'Product ID', 'Process temperature [K]'], axis='columns')
x['Type'] = x['Type'].replace({'M':0, "L":1, "H":2})
y = df['Process temperature [K]']

x.head()

,Type,Air temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,0,298.1,1551,42.8,0,0,0,0,0,0,0
1,1,298.2,1408,46.3,3,0,0,0,0,0,0
2,1,298.1,1498,49.4,5,0,0,0,0,0,0
3,1,298.2,1433,39.5,7,0,0,0,0,0,0
4,1,298.2,1408,40.0,9,0,0,0,0,0,0

In [65]:
model = LinearRegression()
model.fit(x, y)

model.predict([[0,298.1,1551,42.8,0,0,0,0,0,0,0]])

/home/sanjay/Documents/MLOps training/venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([308.75963777])

# Saving the Model

In [66]:
import pickle as pkl
import joblib

In [67]:
with open('multivariate_LR.pkl', 'wb') as file:
    pkl.dump(model, file)

joblib.dump(model, 'multivariate_LR_joblib.pkl')

['multivariate_LR_joblib.pkl']

# One Hot Encoding

In [68]:
x = df.drop(['UDI', 'Product ID', 'Process temperature [K]'], axis='columns')
y = df['Process temperature [K]']

new_x = pd.get_dummies(x, columns=['Type'], dtype=int)
new_x = new_x.drop('Type_M', axis=1)
new_x.head()

,Air temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,Type_H,Type_L
0,298.1,1551,42.8,0,0,0,0,0,0,0,0,0
1,298.2,1408,46.3,3,0,0,0,0,0,0,0,1
2,298.1,1498,49.4,5,0,0,0,0,0,0,0,1
3,298.2,1433,39.5,7,0,0,0,0,0,0,0,1
4,298.2,1408,40.0,9,0,0,0,0,0,0,0,1

In [69]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(new_x, y, test_size=0.2)

model = LinearRegression()
model.fit(x_train, y_train)

model.predict(x_test)

array([308.7231178 , 310.82996101, 309.89543034, ..., 309.15722883,
       308.9161534 , 307.1981955 ], shape=(2000,))

# Logistic Regression

In [70]:
y = df['Machine failure']

x_train, x_test, y_train, y_test = train_test_split(new_x, y, test_size=0.2)
model = LogisticRegression()
model.fit(x_train, y_train)

model.predict(x_test)

array([0, 0, 0, ..., 0, 1, 0], shape=(2000,))